# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
