# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20161025_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
    ]
